# config/packages/tvphotoframe.yaml
# TV Photo Frame with file-based photo storage

# Input Boolean for photo frame control
input_boolean:
  tvphotoframe_enabled:
    name: "Enable Photo Frame"
    initial: true
    icon: mdi:image-multiple

  tvphotoframe_active:
    name: "Photo Frame Active"
    initial: false
    icon: mdi:play-circle

  tvphotoframe_scanning:
    name: "Photo Scanning in Progress"
    initial: false
    icon: mdi:folder-search

# Input Number for interval settings
input_number:
  tvphotoframe_interval:
    name: "Photo Frame Interval (seconds)"
    min: 1
    max: 60
    step: 1
    initial: 5
    unit_of_measurement: "sec"
    icon: mdi:timer

  tv_inactive_timeout:
    name: "TV Inactive Timeout (minutes)"
    min: 1
    max: 30
    step: 1
    initial: 15
    unit_of_measurement: "min"
    icon: mdi:clock-outline

  tvphotoframe_total_photos:
    name: "Total Photo Count"
    min: 0
    max: 10000
    step: 1
    initial: 0
    mode: box
    icon: mdi:counter

# Input Text for settings
input_text:
  tvphotoframe_folder:
    name: "Photo Folder Path"
    initial: "/media/photo/0001photoframe"
    max: 255

# Template sensor for TV activity tracking
template:
  - sensor:
      - name: "LG TV Activity Status"
        unique_id: lg_tv_activity_status
        state: >
          {%- set tv_entity = 'media_player.lg_webos_tv_ur80006lj_2' -%}
          {%- if states(tv_entity) in ['on', 'playing', 'paused', 'idle'] -%}
            {%- if states(tv_entity) == 'playing' -%}
              active
            {%- elif states(tv_entity) in ['paused', 'idle'] -%}
              {%- if state_attr(tv_entity, 'media_title') -%}
                active
              {%- else -%}
                idle
              {%- endif -%}
            {%- else -%}
              idle
            {%- endif -%}
          {%- else -%}
            off
          {%- endif -%}
        attributes:
          tv_entity: "media_player.lg_webos_tv_ur80006lj_2"
          tv_state: "{{ states('media_player.lg_webos_tv_ur80006lj_2') }}"
          media_title: "{{ state_attr('media_player.lg_webos_tv_ur80006lj_2', 'media_title') }}"
          source: "{{ state_attr('media_player.lg_webos_tv_ur80006lj_2', 'source') }}"

# Automations
automation:
  # Start photo frame on TV inactivity
  - id: start_tvphotoframe_on_tv_inactive
    alias: "Start Photo Frame on TV Inactive"
    trigger:
      - platform: state
        entity_id: sensor.lg_tv_activity_status
        to: "idle"
        for:
          minutes: "{{ states('input_number.tv_inactive_timeout') | int }}"
    condition:
      - condition: state
        entity_id: input_boolean.tvphotoframe_enabled
        state: "on"
      - condition: state
        entity_id: input_boolean.tvphotoframe_active
        state: "off"
      - condition: template
        value_template: "{{ states('input_number.tvphotoframe_total_photos') | int > 0 }}"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.tvphotoframe_active
      - service: automation.trigger
        entity_id: automation.tvphotoframe_show_next_photo

  # Stop photo frame on TV activity
  - id: stop_tvphotoframe_on_tv_active
    alias: "Stop Photo Frame on TV Active"
    trigger:
      - platform: state
        entity_id: sensor.lg_tv_activity_status
        to: "active"
      - platform: state
        entity_id: media_player.lg_webos_tv_ur80006lj_2
        attribute: source
      - platform: state
        entity_id: media_player.lg_webos_tv_ur80006lj_2
        attribute: volume_level
    condition:
      - condition: state
        entity_id: input_boolean.tvphotoframe_active
        state: "on"
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.tvphotoframe_active
      - service: media_player.media_stop
        target:
          entity_id: media_player.lg_webos_tv_ur80006lj_2

  # Show next photo (main loop)
  - id: tvphotoframe_show_next_photo
    alias: "Show Next Photo"
    trigger:
      - platform: state
        entity_id: input_boolean.tvphotoframe_active
        to: "on"
      - platform: event
        event_type: automation.triggered
        event_data:
          entity_id: automation.tvphotoframe_show_next_photo
    condition:
      - condition: state
        entity_id: input_boolean.tvphotoframe_active
        state: "on"
      - condition: template
        value_template: "{{ states('sensor.random_photo_path') != 'unavailable' }}"
    action:
      # Get next random photo from Python script
      - service: shell_command.get_next_photo

      # Show photo on TV
      - service: media_player.play_media
        target:
          entity_id: media_player.lg_webos_tv_ur80006lj_2
        data:
          media_content_type: "image/jpeg"
          media_content_id: "{{ states('sensor.random_photo_path') }}"

      # Notification
      - service: notify.persistent_notification
        data:
          message: "Showing photo: {{ state_attr('sensor.random_photo_path', 'photo_file') }}"
          title: "TV Photo Frame"

      # Schedule next photo
      - delay:
          seconds: "{{ states('input_number.tvphotoframe_interval') | int }}"

      # Start next cycle (if photo frame still active)
      - condition: state
        entity_id: input_boolean.tvphotoframe_active
        state: "on"
      - event: automation.triggered
        event_data:
          entity_id: automation.tvphotoframe_show_next_photo

  # Python script for photo loading
  - id: tvphotoframe_run_python_scanner
    alias: "Run Python Photo Scanner"
    trigger:
      - platform: homeassistant
        event: start
      - platform: event
        event_type: tvphotoframe_scan_photos
      - platform: state
        entity_id: input_text.tvphotoframe_folder
    action:
      - delay:
          seconds: 30
      - service: notify.persistent_notification
        data:
          message: "🐍 Running photo scan from folder: {{ states('input_text.tvphotoframe_folder') }}"
          title: "TV Photo Frame"
      - service: shell_command.scan_photos

# Scripts for manual control
script:
  start_tvphotoframe:
    alias: "Start Photo Frame"
    sequence:
      - service: input_boolean.turn_on
        entity_id: input_boolean.tvphotoframe_active

  stop_tvphotoframe:
    alias: "Stop Photo Frame"
    sequence:
      - service: input_boolean.turn_off
        entity_id: input_boolean.tvphotoframe_active

  toggle_tvphotoframe:
    alias: "Toggle Photo Frame"
    sequence:
      - service: input_boolean.toggle
        entity_id: input_boolean.tvphotoframe_active

  next_photo:
    alias: "Next Photo"
    sequence:
      - condition: state
        entity_id: input_boolean.tvphotoframe_active
        state: "on"
      - service: shell_command.get_next_photo

  manual_photo_scan:
    alias: "Manual Photo Scan"
    sequence:
      - service: input_boolean.turn_on
        entity_id: input_boolean.tvphotoframe_scanning
      - service: notify.persistent_notification
        data:
          message: "🐍 Starting photo scan..."
          title: "TV Photo Frame"
      - service: shell_command.scan_photos
      - delay:
          seconds: 5
      - service: input_boolean.turn_off
        entity_id: input_boolean.tvphotoframe_scanning
      - service: notify.persistent_notification
        data:
          message: "✅ Photo scan completed! Check sensor status."
          title: "TV Photo Frame"
